databases:
  - name: django_render_db
    region: singapore
    plan: free
    databaseName: django_render_db
    user: django_user

services:
  - type: web
    name: lbas
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true