# Generated by Django 3.2 on 2023-02-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prebilling_status',
            field=models.BooleanField(default=False),
        ),
    ]
