# Generated by Django 3.2 on 2023-02-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_prebilling_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_expire',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(default=0),
        ),
    ]
