# Generated by Django 4.1.2 on 2024-04-21 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_remove_order_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
